### ISSUE TITLE
Other API Functions

### ISSUE THREAD

**Issue by mcnutter1** [mikenemat/gm-onstar-probe#4]
has anyone mapped the other API functions? Lock/Unlock, Vehicle Status, Location?

**Comment by plucpel** [comment]
I tried unlock but it did not work. I may just not have found the right syntax but could not get it to work. Location I think requires a specific 'plan' from OnStar that is not the basic once included with the car

**Comment by DanH42** [comment]
If you `GET /api/v1/account/vehicles/YOURVIN/commands`, you'll get back a response that partially describes the available commands (converted to YAML to slightly increase readability):
```yaml
- name: cancelAlert
  description: Cancel a vehicle alert (honk horns/flash lights).
  url: https://api.gm.com/api/v1/account/vehicles/YOURVIN/commands/cancelAlert
  isPrivSessionRequired: true
- name: getHotspotInfo
  description: Retrives the WiFi Hotspot info
  url: https://api.gm.com/api/v1/account/vehicles/YOURVIN/hotspot/commands/getInfo
  isPrivSessionRequired: false
- name: lockDoor
  description: Locks the doors.
  url: https://api.gm.com/api/v1/account/vehicles/YOURVIN/commands/lockDoor
  isPrivSessionRequired: true
- name: unlockDoor
  description: Unlocks the doors.
  url: https://api.gm.com/api/v1/account/vehicles/YOURVIN/commands/unlockDoor
  isPrivSessionRequired: true
- name: alert
  description: Triggers a vehicle alert (honk horns/flash lights).
  url: https://api.gm.com/api/v1/account/vehicles/YOURVIN/commands/alert
  isPrivSessionRequired: true
- name: start
  description: Remotely starts the vehicle.
  url: https://api.gm.com/api/v1/account/vehicles/YOURVIN/commands/start
  isPrivSessionRequired: true
- name: cancelStart
  description: Cancels previous remote start command.
  url: https://api.gm.com/api/v1/account/vehicles/YOURVIN/commands/cancelStart
  isPrivSessionRequired: true
- name: diagnostics
  description: Retrieves diagnostic vehicle data.
  url: https://api.gm.com/api/v1/account/vehicles/YOURVIN/commands/diagnostics
  isPrivSessionRequired: false
  commandData:
    supportedDiagnostics:
      supportedDiagnostic:
      - ENGINE COOLANT TEMP
      - ENGINE RPM
      - LAST TRIP FUEL ECONOMY
      - TIRE PRESSURE
      - AMBIENT AIR TEMPERATURE
      - LAST TRIP DISTANCE
      - INTERM VOLT BATT VOLT
      - OIL LIFE
      - LIFETIME FUEL ECON
      - FUEL TANK INFO
      - HOTSPOT CONFIG
      - LIFETIME FUEL USED
      - ODOMETER
      - VEHICLE RANGE
      - HOTSPOT STATUS
- name: sendTBTRoute
  description: Calculates route and initiate download of turn by turn directions to
    the vehicle.
  url: https://api.gm.com/api/v1/account/vehicles/YOURVIN/commands/sendTBTRoute
  isPrivSessionRequired: false
- name: location
  description: Retrieves the vehicle's current location.
  url: https://api.gm.com/api/v1/account/vehicles/YOURVIN/commands/location
  isPrivSessionRequired: true
- name: sendNavDestination
  description: Calculate route and send it to the vehicle's nav unit.
  url: https://api.gm.com/api/v1/account/vehicles/YOURVIN/navUnit/commands/sendNavDestination
  isPrivSessionRequired: false
- name: connect
  description: Initiates a connection to the vehicle
  url: https://api.gm.com/api/v1/account/vehicles/YOURVIN/commands/connect
  isPrivSessionRequired: false
- name: getHotspotStatus
  description: Retrive WiFi status
  url: https://api.gm.com/api/v1/account/vehicles/YOURVIN/hotspot/commands/getStatus
  isPrivSessionRequired: false
- name: setHotspotInfo
  description: update the WiFi SSID and passPhrase
  url: https://api.gm.com/api/v1/account/vehicles/YOURVIN/hotspot/commands/setInfo
  isPrivSessionRequired: true
- name: disableHotspot
  description: Disable WiFi Hotspot
  url: https://api.gm.com/api/v1/account/vehicles/YOURVIN/hotspot/commands/disable
  isPrivSessionRequired: true
- name: enableHotspot
  description: Enable WiFi Hotspot
  url: https://api.gm.com/api/v1/account/vehicles/YOURVIN/hotspot/commands/enable
  isPrivSessionRequired: true
```

This reveals that controlling the doors uses the commands `lockDoor` and `unlockDoor`, rather than the arguably more intuitive `lock` and `unlock` that I also assumed would be the commands. `isPrivSessionRequired` indicates whether or not you're expected to call `/oauth/token/upgrade`.

However, you'll notice that while unlocking works with just `{}` as the request body, requests to lock the doors will be rejected with `{"error":{"code":"ONS-105","description":"Invalid Input."}}`. This took me a while to figure out, but after decompiling the Android app in a (failed) attempt to locate the API keys without needing to use WireShark, I found the classes involved with making these requests, and noticed that the lockDoor command expects a `delay` parameter, wrapped with `lockDoorRequest`. I'm not sure when you'd ever want to send a request to lock the doors at any time other than "right now", so you can probably just stick with a hardcoded `{"lockDoorRequest":{"delay":0}}`.

There's also some additional interesting endpoints that aren't under /commands, and I noticed someone else has already uploaded the decompiled `RemoteAPIService` interface to a [public Gist](https://gist.github.com/tylergets/c5d81d1ca658b2de90c8aff6bf22f988). That class lists all the endpoints that are available to you along with which HTTP method to use, but doesn't include what POST data they expect. I haven't dug into them all, but you can do so yourself if needed by running the myChevrolet APK through [dex2jar](https://github.com/pxb1988/dex2jar) and the passing the result to a tool like [jd-gui](https://github.com/java-decompiler/jd-gui). I'm new to both of those utilities, so you're probably better off reading their documentation yourself rather than me trying to explain them and probably getting things wrong.

I was also particularly interested in pulling diagnostic information, which is also a bit complicated. This endpoint also expects instructions in the request body, and you actually need to list each data point you want to receive. The list is included in the `/commands` response above, but you may want to make that request yourself in case your vehicle responds with a different list of supported diagnostic items. Also the format shown in the response isn't the same as what expects you to send it -- digging into the decompiled Android source once again, I came up with this:

```json
{
  "diagnosticsRequest": {
    "diagnosticItem": [
      "ENGINE COOLANT TEMP",
      "ENGINE RPM",
      "LAST TRIP FUEL ECONOMY",
      "TIRE PRESSURE",
      "AMBIENT AIR TEMPERATURE",
      "LAST TRIP DISTANCE",
      "INTERM VOLT BATT VOLT",
      "OIL LIFE",
      "LIFETIME FUEL ECON",
      "FUEL TANK INFO",
      "LIFETIME FUEL USED",
      "ODOMETER",
      "VEHICLE RANGE"
    ]
  }
}
```

You can change the items in the list as you see fit; the example above requests everything except WiFi hotspot information, which I know I don't care about tracking.

Once you've connected to the vehicle and then sent that request, you should get a 202 Accepted response code, and a JSON object that includes a `commandResponse` object with a `url` property. You'll want to GET that URL (passing the same Authorization header you've been using with every other request) and check for `"status": "success"` in the response object that it returns. You can poll every couple seconds until that's the case, at which point it will also include a `body` with all the diagnostic information data you requested.

Do note that there is a limit to how many consecutive remote requests you're allowed to make. This count does NOT appear to reset with time, and you must instead get into your vehicle and start it yourself. As soon as you do this, your API requests will start working again. When polling at a 30-minute interval, I've been seeing requests start to fail after about 16 requests with `{"error":{"code":"ONS-216","description":"Unable to establish packet session to the vehicle"}}`. I've switched to only polling once an hour, but that was less than 16 hours ago, so we'll see if I get cut off after the same number of requests.

I've just gotten started with this a couple days ago, so I'm by no means an expert, but hopefully the time I spent banging my head against the wall can save a couple other folks from having to go through the same thing.
